# Generated by Django 3.2.25 on 2025-06-20 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('has_expiry', models.BooleanField(default=False)),
                ('has_entry_number', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_removed', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.itemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('expiry_date', models.DateField(null=True)),
                ('entry_number', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.itemmaster')),
            ],
        ),
    ]
