# Generated by Django 3.2.25 on 2025-06-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='has_entry_number',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='has_expiry',
            field=models.BooleanField(blank=True),
        ),
    ]
