# Generated by Django 3.2.25 on 2025-06-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_auto_20250620_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='has_entry_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='has_expiry',
            field=models.BooleanField(default=False),
        ),
    ]
